### ISSUE TITLE
test python3.6 / drop python3.5?

### ISSUE THREAD

**Issue by chriskuehl** [chriskuehl/lazy-build#21]
deadsnakes has python3.6 packages for ubuntu

here are binary and source packages for stretch (a backport from sid): https://www.ocf.berkeley.edu/~ckuehl/python3.6/

**Comment by asottile** [comment]
and here's how you can get it to jive with travis-ci: https://github.com/pre-commit/pre-commit/blob/6e5ac079273c1499add3a85d9b5394d0f1ef1520/.travis.yml#L12-L13
